version: '3.3'

services:
  bb-db:
    image: bb-db:latest
    build:
      context: ./db
    networks:
      - bb-net

  bb-app:
    image: bb-app:latest
    build:
      context: ./app
    ports:
      - "8080:8080"
    depends_on:
      - bb-db
    restart: on-failure
    networks:
      - bb-net

  bb-proxy:
    image: bb-proxy:latest
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - bb-app
    networks:
      - bb-net

networks:
  bb-net:
